spring:
  datasource:
    # 배포 서비스(Railway 등) 환경변수
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # 실제 서비스 데이터 보호
    properties:
      hibernate:
        format_sql: false
        show_sql: false

app:
  base-url: spring-community-platform-production.up.railway.app // 내 배포 주소