spring:
  datasource:
    # 배포 서비스(Railway 등) 환경변수를 사용할 예정입니다. 일단 이렇게 두세요!
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none # 실제 서비스 데이터 보호
    properties:
      hibernate:
        format_sql: false
        show_sql: false

app:
  base-url: https://your-project-url.com # 나중에 배포 주소 생기면 수정할 곳