spring:
  profiles:
    active: dev # 기본값은 dev(로컬)

  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: true

# 로컬과 서버에서 공통으로 읽을 수 있게 바깥으로
app:
  base-url: ${APP_BASE_URL:http://localhost:8080}

resend:
  api:
    key: ${RESEND_API_KEY:dummy_key}